import { db, Platform } from "astro:db";

export const seedPlatforms = async () => {
  await db.insert(Platform).values([
    {
      id: 1,
      name: "Medical",
      description: "Explore medicine, health science, and diagnostics.",
      isActive: true,
      icon: "fa-heartbeat",
      type: "A",
      qCount: 39519,
    },
    {
      id: 2,
      name: "Engineering",
      description: "Explore concepts and disciplines in engineering.",
      isActive: true,
      icon: "fa-cogs",
      type: "P",
      qCount: 21082,
    },
    {
      id: 3,
      name: "Law",
      description: "Understand legal systems, laws, and judiciary concepts.",
      isActive: true,
      icon: "fa-gavel",
      type: "P",
      qCount: 23100,
    },
    {
      id: 4,
      name: "Finance",
      description: "Learn financial planning, markets, and investments.",
      isActive: true,
      icon: "fa-money-bill",
      type: "P",
      qCount: 20949,
    },
    {
      id: 5,
      name: "Driving",
      description: "Practice theory and rules for driving tests.",
      isActive: true,
      icon: "fa-car",
      type: "A",
      qCount: 42338,
    },
    {
      id: 6,
      name: "Government Exams",
      description: "Prepare for various competitive government exams.",
      isActive: true,
      icon: "fa-building",
      type: "A",
      qCount: 26053,
    },
    {
      id: 7,
      name: "Logical Reasoning",
      description: "Sharpen logical thinking and analytical reasoning.",
      isActive: true,
      icon: "fa-brain",
      type: "A",
      qCount: 21373,
    },
    {
      id: 8,
      name: "Mathematics",
      description: "Learn mathematics concepts from basics to advanced.",
      isActive: true,
      icon: "fa-square-root-alt",
      type: "P",
      qCount: 22556,
    },
    {
      id: 9,
      name: "Banking",
      description: "Explore banking services, finance, and operations.",
      isActive: true,
      icon: "fa-flask",
      type: "A",
      qCount: 20818,
    },
    {
      id: 10,
      name: "History",
      description: "Explore major historical events and civilizations.",
      isActive: true,
      icon: "fa-history",
      type: "A",
      qCount: 20709,
    },
    {
      id: 11,
      name: "Geography",
      description: "Study earth’s physical features and human geography.",
      isActive: true,
      icon: "fa-globe-americas",
      type: "A",
      qCount: 23646,
    },
    {
      id: 12,
      name: "Programming",
      description: "Master programming languages and software development.",
      isActive: true,
      icon: "fa-laptop-code",
      type: "P",
      qCount: 196987,
    },
    {
      id: 13,
      name: "Soft Skills",
      description: "Enhance communication, empathy, and people skills.",
      isActive: true,
      icon: "fa-users",
      type: "A",
      qCount: 26794,
    },
    {
      id: 14,
      name: "Language Tests",
      description: "Get ready for global language proficiency exams.",
      isActive: true,
      icon: "fa-comments",
      type: "P",
      qCount: 27363,
    },
    {
      id: 15,
      name: "Business",
      description: "Master business concepts, operations, and strategy.",
      isActive: true,
      icon: "fa-briefcase",
      type: "P",
      qCount: 39357,
    },
    {
      id: 16,
      name: "IT Certifications",
      description: "Prepare for globally recognized IT certification exams.",
      isActive: true,
      icon: "fa-certificate",
      type: "P",
      qCount: 24690,
    },
    {
      id: 17,
      name: "Marketing",
      description: "Develop marketing strategies, branding, and sales skills.",
      isActive: true,
      icon: "fa-bullhorn",
      type: "P",
      qCount: 25071,
    },
    {
      id: 18,
      name: "Physics",
      description: "Understand physics laws and real-world applications.",
      isActive: true,
      icon: "fa-atom",
      type: "A",
      qCount: 22246,
    },
    {
      id: 19,
      name: "Chemistry",
      description: "Master chemical principles and reactions.",
      isActive: true,
      icon: "fa-flask",
      type: "A",
      qCount: 21490,
    },
    {
      id: 20,
      name: "Biology",
      description: "Study the structure, function, and behavior of living organisms.",
      isActive: true,
      icon: "fa-dna",
      type: "A",
      qCount: 21881,
    },
    {
      id: 24,
      name: "General Knowledge",
      description: "Expand your general knowledge across various topics.",
      isActive: true,
      icon: "fa-lightbulb",
      type: "A",
      qCount: 30966,
    },
    {
      id: 29,
      name: "Testing",
      description: "Assess your knowledge through test-based quizzes.",
      isActive: true,
      icon: "fa-vial",
      type: "P",
      qCount: 37531,
    },
    {
      id: 30,
      name: "Entertainment",
      description: "Quiz yourself on movies, music, gaming, and sports.",
      isActive: true,
      icon: "fas fa-film",
      type: "P",
      qCount: 28087,
    },
    {
      id: 31,
      name: "Environmental Science",
      description: "Understand ecosystems, sustainability, and global issues.",
      isActive: true,
      icon: "fa-leaf",
      type: "A",
      qCount: 26672,
    },
    {
      id: 32,
      name: "Arts & Humanities",
      description: "Dive into arts, culture, literature, and philosophy.",
      isActive: true,
      icon: "fa-palette",
      type: "A",
      qCount: 76848,
    },
    {
      id: 33,
      name: "Travel & Tourism",
      description: "Explore destinations, travel tips, and tourism management.",
      isActive: true,
      icon: "fa-plane",
      type: "P",
      qCount: 22591,
    },
    {
      id: 34,
      name: "Psychology",
      description: "Study the mind, behavior, and mental health theories.",
      isActive: true,
      icon: "fa-user-nurse",
      type: "A",
      qCount: 21173,
    },
    {
      id: 35,
      name: "Mechanical Skills",
      description: "Learn about tools, machines, engines, and mechanics.",
      isActive: true,
      icon: "fa-wrench",
      type: "P",
      qCount: 21316,
    },
    {
      id: 36,
      name: "Culture & Mythology",
      description: "Explore ancient myths, folklore, and cultural heritage.",
      isActive: true,
      icon: "fa-landmark",
      type: "A",
      qCount: 22332,
    },
    {
      id: 37,
      name: "Education & Teaching",
      description: "Focus on teaching strategies, pedagogy, and education systems.",
      isActive: true,
      icon: "fa-chalkboard-teacher",
      type: "P",
      qCount: 20870,
    },
    {
      id: 38,
      name: "Networking",
      description: "Learn about networking protocols, security, and systems.",
      isActive: true,
      icon: "fa-network-wired",
      type: "P",
      qCount: 22752,
    },
    {
      id: 39,
      name: "Ethics and Philosophy",
      description: "Explore moral philosophy, logic, and critical reasoning.",
      isActive: true,
      icon: "fa-balance-scale",
      type: "A",
      qCount: 28203,
    },
    {
      id: 40,
      name: "Astronomy & Space",
      description: "Learn about planets, galaxies, space exploration, and the universe.",
      isActive: true,
      icon: "fa-satellite-dish",
      type: "A",
      qCount: 20983,
    },
    {
      id: 41,
      name: "Economics",
      description: "Understand economic theories, markets, trade, and global development.",
      isActive: true,
      icon: "fa-chart-line",
      type: "A",
      qCount: 22768,
    },
    {
      id: 42,
      name: "Languages & Literature",
      description: "Dive into grammar, prose, poetry, world literature, and comprehension.",
      isActive: true,
      icon: "fa-book-open",
      type: "A",
      qCount: 23633,
    },
    {
      id: 43,
      name: "Health & Nutrition",
      description: "Focus on wellness, dietary habits, exercise, and preventive care.",
      isActive: true,
      icon: "fa-apple-alt",
      type: "A",
      qCount: 20604,
    },
    {
      id: 44,
      name: "Ethical Hacking & Cybersecurity",
      description: "Learn about penetration testing, threat mitigation, and cyber protection.",
      isActive: true,
      icon: "fa-user-secret",
      type: "P",
      qCount: 21061,
    },
    {
      id: 45,
      name: "Civics & Governance",
      description: "Understand political systems, constitutional law, and civic responsibilities.",
      isActive: true,
      icon: "fa-landmark",
      type: "A",
      qCount: 36815,
    },
    {
      id: 46,
      name: "Wellness & Lifestyle",
      description: "Improve mental and physical well-being through mindfulness and healthy living.",
      isActive: true,
      icon: "fa-spa",
      type: "A",
      qCount: 111147,
    },
    {
      id: 47,
      name: "Quantitative Aptitude",
      description: "Master arithmetic and problem-solving for competitive exams.",
      isActive: true,
      icon: "fa-divide",
      type: "A",
      qCount: 56896,
    },
    {
      id: 48,
      name: "Culinary Arts",
      description: "Learn cooking methods, nutrition, and kitchen safety.",
      isActive: true,
      icon: "fa-utensils",
      type: "P",
      qCount: 27877,
    },
    {
      id: 49,
      name: "Architecture & Urban Planning",
      description: "Design spaces and understand the principles of urban development.",
      isActive: false,
      icon: "fa-drafting-compass",
      type: "P",
      qCount: 0,
    },
    {
      id: 50,
      name: "Design & UX",
      description: "Create user-centered digital experiences and visual designs.",
      isActive: false,
      icon: "fa-paint-brush",
      type: "P",
      qCount: 0,
    },
    {
      id: 51,
      name: "Higher Education Prep",
      description: "Prepare for GRE, GMAT, TOEFL, IELTS, and other academic exams.",
      isActive: false,
      icon: "fa-university",
      type: "P",
      qCount: 0,
    },
    {
      id: 52,
      name: "Game Design & Theory",
      description: "Understand game mechanics, user psychology, and development tools.",
      isActive: false,
      icon: "fa-gamepad",
      type: "P",
      qCount: 0,
    },
    {
      id: 53,
      name: "School",
      description:
        "Quiz content aligned with Indian school syllabi across various state and national boards for SSLC, +1, and +2 levels.",
      isActive: true,
      icon: "fa-school",
      type: "A",
      qCount: 59374,
    },
  ]);
};
