import { db, Subject } from "astro:db";

export const seedSubjects = async () => {
  await db.insert(Subject).values([
    { id: 1, platformId: 12, isActive: true, name: "Web Development", qCount: 21508 },
    { id: 2, platformId: 12, isActive: true, name: "Mobile Development", qCount: 9140 },
    { id: 3, platformId: 12, isActive: true, name: "Data Structures & Algorithms", qCount: 9378 },
    { id: 4, platformId: 12, isActive: true, name: "Databases", qCount: 40848 },
    { id: 5, platformId: 12, isActive: true, name: "Cybersecurity", qCount: 5175 },
    { id: 6, platformId: 12, isActive: true, name: "Cloud Computing", qCount: 8388 },
    { id: 7, platformId: 12, isActive: true, name: "DevOps", qCount: 6260 },
    { id: 8, platformId: 12, isActive: true, name: "Software Engineering", qCount: 6718 },
    { id: 9, platformId: 12, isActive: true, name: "Game Development", qCount: 9967 },
    { id: 10, platformId: 12, isActive: true, name: "Machine Learning", qCount: 7550 },
    { id: 11, platformId: 7, isActive: true, name: "Verbal Reasoning", qCount: 4482 },
    { id: 12, platformId: 7, isActive: true, name: "Non-Verbal Reasoning", qCount: 4206 },
    { id: 13, platformId: 7, isActive: true, name: "Analytical Reasoning", qCount: 5099 },
    { id: 14, platformId: 7, isActive: true, name: "Critical Thinking", qCount: 4191 },
    { id: 15, platformId: 7, isActive: true, name: "Puzzles & Brain Teasers", qCount: 3395 },
    { id: 16, platformId: 16, isActive: true, name: "Cloud Computing", qCount: 3943 },
    { id: 17, platformId: 16, isActive: true, name: "Cybersecurity", qCount: 3139 },
    { id: 18, platformId: 16, isActive: true, name: "Networking", qCount: 2887 },
    { id: 19, platformId: 16, isActive: true, name: "Software Development", qCount: 3490 },
    { id: 20, platformId: 16, isActive: true, name: "Database Management", qCount: 4072 },
    { id: 21, platformId: 16, isActive: true, name: "IT Service Management", qCount: 3234 },
    { id: 22, platformId: 16, isActive: true, name: "DevOps & Automation", qCount: 3925 },
    { id: 23, platformId: 6, isActive: true, name: "Civil Services", qCount: 4388 },
    { id: 24, platformId: 6, isActive: true, name: "Banking Exams", qCount: 3442 },
    { id: 25, platformId: 6, isActive: true, name: "Railway Exams", qCount: 3428 },
    { id: 26, platformId: 6, isActive: true, name: "SSC Exams", qCount: 3935 },
    { id: 27, platformId: 6, isActive: true, name: "Defence Exams", qCount: 3864 },
    { id: 28, platformId: 6, isActive: true, name: "State Government Exams", qCount: 3206 },
    { id: 29, platformId: 6, isActive: true, name: "Teaching Eligibility Tests", qCount: 3790 },
    { id: 30, platformId: 3, isActive: true, name: "Law Entrance Exams", qCount: 3733 },
    { id: 31, platformId: 3, isActive: true, name: "Judiciary Exams", qCount: 3347 },
    { id: 32, platformId: 3, isActive: true, name: "Corporate Law", qCount: 3934 },
    { id: 33, platformId: 3, isActive: true, name: "Constitutional Law", qCount: 3375 },
    { id: 34, platformId: 3, isActive: true, name: "Criminal Law", qCount: 4941 },
    { id: 35, platformId: 3, isActive: true, name: "International Law", qCount: 3770 },
    { id: 36, platformId: 1, isActive: true, name: "Medical Entrance Exams", qCount: 4183 },
    { id: 37, platformId: 1, isActive: true, name: "Pre-Clinical Subjects", qCount: 3613 },
    { id: 38, platformId: 1, isActive: true, name: "Para-Clinical Subjects", qCount: 4347 },
    { id: 39, platformId: 1, isActive: true, name: "Clinical Subjects", qCount: 8919 },
    { id: 40, platformId: 1, isActive: true, name: "Medical Specializations", qCount: 7348 },
    { id: 41, platformId: 2, isActive: true, name: "Engineering Entrance Exams", qCount: 4105 },
    { id: 42, platformId: 2, isActive: true, name: "Core Engineering Subjects", qCount: 8300 },
    { id: 43, platformId: 2, isActive: true, name: "Specialized Engineering Fields", qCount: 8677 },
    { id: 44, platformId: 4, isActive: true, name: "Financial Markets and Instruments", qCount: 5048 },
    { id: 45, platformId: 4, isActive: true, name: "Corporate Finance and Accounting", qCount: 5436 },
    { id: 46, platformId: 4, isActive: true, name: "Investment Management", qCount: 3838 },
    { id: 47, platformId: 4, isActive: true, name: "Personal Finance", qCount: 3791 },
    { id: 48, platformId: 4, isActive: true, name: "Risk Management", qCount: 2836 },
    { id: 49, platformId: 5, isActive: true, name: "Road Signs and Signals", qCount: 7025 },
    { id: 50, platformId: 5, isActive: true, name: "Traffic Rules and Regulations", qCount: 8314 },
    { id: 51, platformId: 5, isActive: true, name: "Vehicle Operation and Control", qCount: 9005 },
    { id: 52, platformId: 5, isActive: true, name: "Safety Procedures and Emergency Handling", qCount: 9303 },
    { id: 53, platformId: 5, isActive: true, name: "Environmental Impact and Eco-driving", qCount: 8691 },
    { id: 54, platformId: 8, isActive: true, name: "Algebra", qCount: 4551 },
    { id: 55, platformId: 8, isActive: true, name: "Geometry", qCount: 4661 },
    { id: 56, platformId: 8, isActive: true, name: "Calculus", qCount: 5045 },
    { id: 57, platformId: 8, isActive: true, name: "Probability", qCount: 4629 },
    { id: 58, platformId: 8, isActive: true, name: "Statistics", qCount: 3670 },
    { id: 59, platformId: 10, isActive: true, name: "Ancient History", qCount: 6605 },
    { id: 60, platformId: 10, isActive: true, name: "Medieval History", qCount: 6526 },
    { id: 61, platformId: 10, isActive: true, name: "Modern History", qCount: 7578 },
    { id: 62, platformId: 11, isActive: true, name: "Physical Geography", qCount: 8793 },
    { id: 63, platformId: 11, isActive: true, name: "Human Geography", qCount: 7196 },
    { id: 64, platformId: 11, isActive: true, name: "Environmental Geography", qCount: 7657 },
    { id: 65, platformId: 13, isActive: true, name: "Communication Skills", qCount: 7712 },
    { id: 66, platformId: 13, isActive: true, name: "Leadership Skills", qCount: 6159 },
    { id: 67, platformId: 13, isActive: true, name: "Team Work", qCount: 6476 },
    { id: 68, platformId: 13, isActive: true, name: "Time Management", qCount: 6447 },
    { id: 73, platformId: 15, isActive: true, name: "Management", qCount: 5286 },
    { id: 74, platformId: 15, isActive: true, name: "Marketing", qCount: 3654 },
    { id: 75, platformId: 15, isActive: true, name: "Finance", qCount: 4769 },
    { id: 76, platformId: 15, isActive: true, name: "Entrepreneurship", qCount: 4570 },
    { id: 85, platformId: 17, isActive: true, name: "Marketing Fundamentals", qCount: 6334 },
    { id: 86, platformId: 17, isActive: true, name: "Digital Marketing", qCount: 6723 },
    { id: 87, platformId: 17, isActive: true, name: "Social Media Marketing", qCount: 6733 },
    { id: 88, platformId: 17, isActive: true, name: "Brand Management", qCount: 5281 },
    { id: 89, platformId: 18, isActive: true, name: "Classical Mechanics", qCount: 5850 },
    { id: 90, platformId: 18, isActive: true, name: "Quantum Physics", qCount: 3730 },
    { id: 91, platformId: 18, isActive: true, name: "Thermodynamics", qCount: 1693 },
    { id: 92, platformId: 18, isActive: true, name: "Electromagnetism", qCount: 3455 },
    { id: 93, platformId: 18, isActive: true, name: "Optics", qCount: 4216 },
    { id: 94, platformId: 18, isActive: true, name: "Nuclear Physics", qCount: 3302 },
    { id: 95, platformId: 19, isActive: true, name: "Organic Chemistry", qCount: 5581 },
    { id: 96, platformId: 19, isActive: true, name: "Inorganic Chemistry", qCount: 4246 },
    { id: 97, platformId: 19, isActive: true, name: "Physical Chemistry", qCount: 3935 },
    { id: 98, platformId: 19, isActive: true, name: "Analytical Chemistry", qCount: 4352 },
    { id: 99, platformId: 19, isActive: true, name: "Biochemistry", qCount: 3376 },
    { id: 100, platformId: 20, isActive: true, name: "Botany", qCount: 5993 },
    { id: 101, platformId: 20, isActive: true, name: "Zoology", qCount: 4990 },
    { id: 102, platformId: 20, isActive: true, name: "Microbiology", qCount: 3906 },
    { id: 103, platformId: 20, isActive: true, name: "Genetics", qCount: 3628 },
    { id: 104, platformId: 20, isActive: true, name: "Biotechnology", qCount: 3364 },
    { id: 105, platformId: 9, isActive: true, name: "Banking Basics", qCount: 4222 },
    { id: 106, platformId: 9, isActive: true, name: "Financial Instruments", qCount: 4752 },
    { id: 107, platformId: 9, isActive: true, name: "Banking Operations", qCount: 3525 },
    { id: 108, platformId: 9, isActive: true, name: "Risk Management in Banking", qCount: 3352 },
    { id: 109, platformId: 9, isActive: true, name: "Banking Regulations", qCount: 4967 },
    { id: 138, platformId: 14, isActive: true, name: "English Proficiency", qCount: 6714 },
    { id: 139, platformId: 14, isActive: true, name: "French", qCount: 6716 },
    { id: 140, platformId: 14, isActive: true, name: "Spanish", qCount: 7092 },
    { id: 141, platformId: 14, isActive: true, name: "German", qCount: 6841 },
    { id: 142, platformId: 12, isActive: true, name: "Artificial Intelligence", qCount: 19257 },
    { id: 144, platformId: 24, isActive: true, name: "History", qCount: 3095 },
    { id: 145, platformId: 24, isActive: true, name: "Geography", qCount: 2098 },
    { id: 146, platformId: 24, isActive: true, name: "Science", qCount: 2919 },
    { id: 147, platformId: 24, isActive: true, name: "Sports", qCount: 2677 },
    { id: 148, platformId: 24, isActive: true, name: "Politics", qCount: 1721 },
    { id: 149, platformId: 24, isActive: true, name: "Art & Literature", qCount: 3469 },
    { id: 150, platformId: 24, isActive: true, name: "Technology", qCount: 3674 },
    { id: 151, platformId: 24, isActive: true, name: "Economy", qCount: 3503 },
    { id: 152, platformId: 24, isActive: true, name: "Culture", qCount: 4148 },
    { id: 153, platformId: 24, isActive: true, name: "Current Affairs", qCount: 3662 },
    { id: 155, platformId: 12, isActive: true, name: "Programming Languages", qCount: 52798 },
    { id: 156, platformId: 29, isActive: true, name: "Manual Testing", qCount: 3485 },
    { id: 157, platformId: 29, isActive: true, name: "Automation Testing", qCount: 4662 },
    { id: 158, platformId: 29, isActive: true, name: "Performance Testing", qCount: 3566 },
    { id: 159, platformId: 29, isActive: true, name: "API Testing", qCount: 3320 },
    { id: 160, platformId: 29, isActive: true, name: "Security Testing", qCount: 2988 },
    { id: 161, platformId: 29, isActive: true, name: "Mobile Testing", qCount: 4376 },
    { id: 162, platformId: 29, isActive: true, name: "Database Testing", qCount: 3504 },
    { id: 163, platformId: 29, isActive: true, name: "DevOps for Testers", qCount: 3329 },
    { id: 164, platformId: 29, isActive: true, name: "Agile Testing", qCount: 3491 },
    { id: 165, platformId: 29, isActive: true, name: "Testing Tools and Technologies", qCount: 4810 },
    { id: 166, platformId: 30, isActive: true, name: "Movies & TV Shows", qCount: 3129 },
    { id: 167, platformId: 30, isActive: true, name: "Music", qCount: 3450 },
    { id: 168, platformId: 30, isActive: true, name: "Sports", qCount: 3002 },
    { id: 169, platformId: 30, isActive: true, name: "Video Games", qCount: 3496 },
    { id: 170, platformId: 30, isActive: true, name: "Celebrities & Pop Culture", qCount: 2679 },
    { id: 171, platformId: 30, isActive: true, name: "Cartoons & Animation", qCount: 2761 },
    { id: 172, platformId: 30, isActive: true, name: "Streaming Platforms", qCount: 2812 },
    { id: 173, platformId: 30, isActive: true, name: "Comics & Superheroes", qCount: 2585 },
    { id: 174, platformId: 30, isActive: true, name: "Award Shows & Ceremonies", qCount: 2200 },
    { id: 175, platformId: 30, isActive: true, name: "World Records & Fun Facts", qCount: 1973 },
    { id: 176, platformId: 31, isActive: true, name: "Environmental Studies", qCount: 2007 },
    { id: 177, platformId: 31, isActive: true, name: "Climate Change", qCount: 2781 },
    { id: 178, platformId: 31, isActive: true, name: "Sustainability", qCount: 2414 },
    { id: 179, platformId: 31, isActive: true, name: "Renewable Energy", qCount: 3249 },
    { id: 180, platformId: 31, isActive: true, name: "Ecology", qCount: 2917 },
    { id: 181, platformId: 31, isActive: true, name: "Environmental Policy", qCount: 3639 },
    { id: 182, platformId: 31, isActive: true, name: "Conservation Science", qCount: 2400 },
    { id: 183, platformId: 31, isActive: true, name: "Pollution & Waste Management", qCount: 3657 },
    { id: 184, platformId: 31, isActive: true, name: "Earth Science", qCount: 3608 },
    { id: 185, platformId: 32, isActive: true, name: "Literature", qCount: 7514 },
    { id: 186, platformId: 32, isActive: true, name: "History of Art", qCount: 8122 },
    { id: 187, platformId: 32, isActive: true, name: "Philosophy", qCount: 6931 },
    { id: 188, platformId: 32, isActive: true, name: "Music", qCount: 7582 },
    { id: 189, platformId: 32, isActive: true, name: "Visual Arts", qCount: 7262 },
    { id: 190, platformId: 32, isActive: true, name: "Performing Arts", qCount: 9215 },
    { id: 191, platformId: 32, isActive: true, name: "Linguistics", qCount: 7360 },
    { id: 192, platformId: 32, isActive: true, name: "Cultural Studies", qCount: 6242 },
    { id: 193, platformId: 32, isActive: true, name: "World History", qCount: 7561 },
    { id: 194, platformId: 32, isActive: true, name: "Religion & Mythology", qCount: 9059 },
    { id: 195, platformId: 33, isActive: true, name: "Travel Destinations", qCount: 4332 },
    { id: 196, platformId: 33, isActive: true, name: "Travel Planning", qCount: 4458 },
    { id: 197, platformId: 33, isActive: true, name: "Hospitality Management", qCount: 4669 },
    { id: 198, platformId: 33, isActive: true, name: "World Cultures", qCount: 4989 },
    { id: 199, platformId: 33, isActive: true, name: "Tourism Geography", qCount: 4143 },
    { id: 200, platformId: 34, isActive: true, name: "General Psychology", qCount: 3171 },
    { id: 201, platformId: 34, isActive: true, name: "Developmental Psychology", qCount: 4170 },
    { id: 202, platformId: 34, isActive: true, name: "Abnormal Psychology", qCount: 5537 },
    { id: 203, platformId: 34, isActive: true, name: "Social Psychology", qCount: 4109 },
    { id: 204, platformId: 34, isActive: true, name: "Cognitive Psychology", qCount: 4186 },
    { id: 205, platformId: 35, isActive: true, name: "Basic Mechanics", qCount: 4528 },
    { id: 206, platformId: 35, isActive: true, name: "Automobile Technology", qCount: 4869 },
    { id: 207, platformId: 35, isActive: true, name: "Industrial Machinery", qCount: 4393 },
    { id: 208, platformId: 35, isActive: true, name: "Engineering Drawing", qCount: 3853 },
    { id: 209, platformId: 35, isActive: true, name: "Maintenance & Repair", qCount: 3673 },
    { id: 210, platformId: 36, isActive: true, name: "World Mythologies", qCount: 5469 },
    { id: 211, platformId: 36, isActive: true, name: "Cultural Anthropology", qCount: 4407 },
    { id: 212, platformId: 36, isActive: true, name: "Folklore and Legends", qCount: 4456 },
    { id: 213, platformId: 36, isActive: true, name: "World Religions", qCount: 4220 },
    { id: 214, platformId: 36, isActive: true, name: "Festivals and Traditions", qCount: 3780 },
    { id: 215, platformId: 37, isActive: true, name: "Teaching Methodologies", qCount: 3954 },
    { id: 216, platformId: 37, isActive: true, name: "Curriculum Development", qCount: 3913 },
    { id: 217, platformId: 37, isActive: true, name: "Educational Psychology", qCount: 4263 },
    { id: 218, platformId: 37, isActive: true, name: "Instructional Technology", qCount: 4544 },
    { id: 219, platformId: 37, isActive: true, name: "Assessment & Evaluation", qCount: 4196 },
    { id: 220, platformId: 38, isActive: true, name: "Computer Networks Basics", qCount: 5261 },
    { id: 221, platformId: 38, isActive: true, name: "IP Addressing and Subnetting", qCount: 3398 },
    { id: 222, platformId: 38, isActive: true, name: "Protocols and Ports", qCount: 4881 },
    { id: 223, platformId: 38, isActive: true, name: "Network Security", qCount: 4702 },
    { id: 224, platformId: 38, isActive: true, name: "Wireless and Mobile Networks", qCount: 4510 },
    { id: 524, platformId: 39, isActive: true, name: "Moral Philosophy", qCount: 2965 },
    { id: 525, platformId: 39, isActive: true, name: "Philosophy of Mind", qCount: 2719 },
    { id: 526, platformId: 39, isActive: true, name: "Political Philosophy", qCount: 4624 },
    { id: 527, platformId: 40, isActive: true, name: "Solar System Exploration", qCount: 5321 },
    { id: 528, platformId: 40, isActive: true, name: "Stars and Galaxies", qCount: 4579 },
    { id: 529, platformId: 40, isActive: true, name: "Cosmology", qCount: 4653 },
    { id: 530, platformId: 40, isActive: true, name: "Space Missions", qCount: 6430 },
    { id: 531, platformId: 41, isActive: true, name: "Microeconomics", qCount: 6914 },
    { id: 532, platformId: 41, isActive: true, name: "Macroeconomics", qCount: 4808 },
    { id: 533, platformId: 41, isActive: true, name: "International Trade", qCount: 5781 },
    { id: 534, platformId: 41, isActive: true, name: "Development Economics", qCount: 5265 },
    { id: 535, platformId: 42, isActive: true, name: "English Grammar", qCount: 6402 },
    { id: 536, platformId: 42, isActive: true, name: "World Literature", qCount: 6747 },
    { id: 537, platformId: 42, isActive: true, name: "Poetry and Prose", qCount: 5550 },
    { id: 538, platformId: 42, isActive: true, name: "Reading Comprehension", qCount: 4934 },
    { id: 539, platformId: 43, isActive: true, name: "Human Nutrition", qCount: 6624 },
    { id: 540, platformId: 43, isActive: true, name: "Fitness and Exercise", qCount: 4866 },
    { id: 541, platformId: 43, isActive: true, name: "Preventive Healthcare", qCount: 4764 },
    { id: 542, platformId: 43, isActive: true, name: "Mental Health Awareness", qCount: 4350 },
    { id: 543, platformId: 44, isActive: true, name: "Ethical Hacking Basics", qCount: 5393 },
    { id: 544, platformId: 44, isActive: true, name: "Web Application Security", qCount: 4419 },
    { id: 545, platformId: 44, isActive: true, name: "Network Securities", qCount: 6049 },
    { id: 546, platformId: 44, isActive: true, name: "Cyber Law and Ethics", qCount: 5200 },
    { id: 547, platformId: 1, isActive: true, name: "Nursing", qCount: 11109 },
    { id: 548, platformId: 45, isActive: true, name: "Constitutional Studies", qCount: 6889 },
    { id: 549, platformId: 45, isActive: true, name: "Public Administration", qCount: 7774 },
    { id: 550, platformId: 45, isActive: true, name: "World Politics", qCount: 7538 },
    { id: 551, platformId: 45, isActive: true, name: "Indian Political System", qCount: 7545 },
    { id: 552, platformId: 45, isActive: true, name: "Civic Awareness", qCount: 7069 },
    { id: 643, platformId: 53, isActive: true, name: "Tamil Nadu State Board", qCount: 10024 },
    { id: 644, platformId: 53, isActive: true, name: "Karnataka SSLC & PUC", qCount: 8042 },
    { id: 645, platformId: 53, isActive: true, name: "Kerala Board of Public Examinations", qCount: 9377 },
    {
      id: 646,
      platformId: 53,
      isActive: true,
      name: "Maharashtra State Board (MSBSHSE)",
      qCount: 10604,
    },
    { id: 647, platformId: 53, isActive: true, name: "CBSE", qCount: 10808 },
    {
      id: 648,
      platformId: 53,
      isActive: true,
      name: "Andhra Pradesh / Telangana (BIE/APSCHE)",
      qCount: 10519,
    },
    { id: 649, platformId: 48, isActive: true, name: "Fundamentals of Cooking", qCount: 4655 },
    { id: 650, platformId: 48, isActive: true, name: "Cuisines of the World", qCount: 7613 },
    { id: 651, platformId: 48, isActive: true, name: "Nutrition & Dietetics", qCount: 5511 },
    { id: 652, platformId: 48, isActive: true, name: "Baking & Pastry Arts", qCount: 5923 },
    { id: 653, platformId: 48, isActive: true, name: "Food Presentation & Service", qCount: 4175 },
    { id: 654, platformId: 15, isActive: true, name: "Salesforce", qCount: 21078 },
    { id: 655, platformId: 47, isActive: true, name: "Arithmetic", qCount: 9034 },
    { id: 656, platformId: 47, isActive: true, name: "Algebra", qCount: 4969 },
    { id: 657, platformId: 47, isActive: true, name: "Geometry", qCount: 5393 },
    { id: 658, platformId: 47, isActive: true, name: "Mensuration", qCount: 3305 },
    { id: 659, platformId: 47, isActive: true, name: "Trigonometry", qCount: 2557 },
    { id: 660, platformId: 47, isActive: true, name: "Probability", qCount: 2399 },
    {
      id: 661,
      platformId: 47,
      isActive: true,
      name: "Statistics & Data Interpretation",
      qCount: 5724,
    },
    { id: 662, platformId: 47, isActive: true, name: "Number System", qCount: 3663 },
    {
      id: 663,
      platformId: 47,
      isActive: true,
      name: "Permutations & Combinations",
      qCount: 3328,
    },
    { id: 664, platformId: 47, isActive: true, name: "Time, Speed & Distance", qCount: 3784 },
    { id: 665, platformId: 47, isActive: true, name: "Time & Work", qCount: 2197 },
    { id: 666, platformId: 47, isActive: true, name: "Ratio & Proportion", qCount: 2338 },
    {
      id: 667,
      platformId: 47,
      isActive: true,
      name: "Percentages & Profit & Loss",
      qCount: 4355,
    },
    { id: 668, platformId: 47, isActive: true, name: "Simple & Compound Interest", qCount: 3850 },
    { id: 669, platformId: 39, isActive: true, name: "Logic & Critical Thinking", qCount: 3733 },
    { id: 670, platformId: 39, isActive: true, name: "Metaphysics", qCount: 4866 },
    { id: 671, platformId: 39, isActive: true, name: "Philosophy of Religion", qCount: 4481 },
    { id: 672, platformId: 39, isActive: true, name: "Aesthetics", qCount: 4815 },
    { id: 673, platformId: 46, isActive: true, name: "Mental Health", qCount: 5508 },
    { id: 674, platformId: 46, isActive: true, name: "Mindfulness & Meditation", qCount: 5960 },
    { id: 675, platformId: 46, isActive: true, name: "Stress Management", qCount: 5592 },
    { id: 676, platformId: 46, isActive: true, name: "Sleep Science & Hygiene", qCount: 5499 },
    { id: 677, platformId: 46, isActive: true, name: "Nutrition & Diet", qCount: 5675 },
    { id: 678, platformId: 46, isActive: true, name: "Fitness & Exercise Science", qCount: 6066 },
    {
      id: 679,
      platformId: 46,
      isActive: true,
      name: "Habit Building & Behavior Change",
      qCount: 5864,
    },
    {
      id: 680,
      platformId: 46,
      isActive: true,
      name: "Time Management & Productivity",
      qCount: 5282,
    },
    { id: 681, platformId: 46, isActive: true, name: "Emotional Intelligence", qCount: 5845 },
    { id: 682, platformId: 46, isActive: true, name: "Relationships & Communication", qCount: 5621 },
    { id: 683, platformId: 46, isActive: true, name: "Self-Care & Resilience", qCount: 6066 },
    { id: 684, platformId: 46, isActive: true, name: "Digital Wellbeing", qCount: 5366 },
    {
      id: 685,
      platformId: 46,
      isActive: true,
      name: "Work–Life Balance & Burnout",
      qCount: 6024,
    },
    { id: 686, platformId: 46, isActive: true, name: "Positive Psychology", qCount: 6035 },
    { id: 687, platformId: 46, isActive: true, name: "Yoga & Breathwork", qCount: 6651 },
    { id: 688, platformId: 46, isActive: true, name: "Longevity & Healthy Aging", qCount: 5652 },
    { id: 689, platformId: 46, isActive: true, name: "Women's Health", qCount: 6093 },
    { id: 690, platformId: 46, isActive: true, name: "Men's Health", qCount: 6499 },
    { id: 691, platformId: 46, isActive: true, name: "Substance Use & Recovery", qCount: 5849 },
  ]);
};
